### ISSUE TITLE
bug rport

### ISSUE THREAD

**Issue by Summer-Koi** [hyperNeptune/hyperNepDB#6]
FIXME: 

ThssDB2023>select * from test;
col1, col2, col3, col4, col5
----------------------------------------------------------------
1, 1.0, nocturne, 2.2, 1000
It costs 7 ms.
ThssDB2023>select col1 from test;
col1
----------------------------------------------------------------
1
It costs 1 ms.
ThssDB2023>select col3 from test;
null
It costs 0 ms.
ThssDB2023>select col3 from test;
null
It costs 1 ms.
ThssDB2023>select * from test;
col1, col2, col3, col4, col5
----------------------------------------------------------------
1, 1.0, nocturne, 2.2, 1000
It costs 1 ms.
ThssDB2023>

FIXME: calculator

**Comment by Wang-Ji20** [comment]
I fixed the select bug. God Damn Java reference system caused this problem.
I copy the reference to one column of the original schema to my projection output tuple. then my projector changed the column, and the original column was changed too..

**Comment by Wang-Ji20** [comment]
calculator is in low priority. it needs the change of whole binder system. better leave it be, and hu nong this hw. Java is not fit for a cool dbms anyway
